# Central config for analysis + plotting

paths:
  # roots (absolute or relative to $HOME)
  png_per_cloud_root: scratch/all_clouds_data/threshold_autocorr_bd/per_cloud
  png_meta_root:      scratch/all_clouds_data/threshold_autocorr_bd
  sp_per_cloud_root:  scratch/all_clouds_data/sp_autocorr_bd/per_cloud

  out:
    fd:         scratch/all_clouds_data/analysis/fractal_dimension
    autocorr:   scratch/all_clouds_data/analysis/autocorr
    bdd:        scratch/all_clouds_data/analysis/bd_distribution

png:
  time_windows: []      # e.g. ["03:00-04:00","04:00-05:00","all"]
  threshold_policy: argmax_clouds   # "all" | "argmax_clouds"
  thresholds_whitelist: null        # when threshold_policy == "all"
  on_missing_metadata: skip_run     # "skip_run" | "keep_all_thresholds"

siteperc:
  p_vals: null          # e.g. [0.4074]  ; null => accept all

filters:
  min_area: 500
  max_area: 7500000
  min_perim: null
  max_perim: null

plot_defaults:
  figsize: [9.0, 7.0]
  dpi: 300
  line_width: 2.0
  grid_lw: 0.8
  grid_alpha: 0.8

plot_overlay:
  legend: stem       # stem | name
  bdd_min_coverage: 0
  autocorr_field: agg_ratio  # agg_ratio | agg_num | agg_den | y
  logx: false
  logy: false
